
export const simpleDoctorsData = [
  {
    id: '1',
    name: 'Александр Иванов',
    specialty: 'Терапевт',
    rating: 4.7,
    experience: 12,
    price: 2000,
    description: 'Опытный терапевт с более чем 10-летним стажем. Специализируется на лечении острых респираторных заболеваний и профилактике хронических болезней.',
    photoUrl: 'https://example.com/doctor1.jpg',
    reviewCount: 24,
  },
  {
    id: '2',
    name: 'Мария Петрова',
    specialty: 'Кардиолог',
    rating: 4.9,
    experience: 15,
    price: 3500,
    description: 'Кардиолог высшей категории. Проводит диагностику и лечение сердечно-сосудистых заболеваний. Автор научных публикаций.',
    photoUrl: 'https://example.com/doctor2.jpg',
    reviewCount: 18,
  },
  {
    id: '3',
    name: 'Сергей Сидоров',
    specialty: 'Невролог',
    rating: 4.5,
    experience: 8,
    price: 2800,
    description: 'Специалист по заболеваниям нервной системы. Использует современные методы диагностики и лечения.',
    photoUrl: 'https://example.com/doctor3.jpg',
    reviewCount: 15,
  },
  {
    id: '4',
    name: 'Елена Кузнецова',
    specialty: 'Педиатр',
    rating: 4.8,
    experience: 10,
    price: 1800,
    description: 'Детский врач с большим опытом работы. Особое внимание уделяет профилактическим осмотрам и вакцинации.',
    photoUrl: 'https://example.com/doctor4.jpg',
    reviewCount: 32,
  },
  {
    id: '5',
    name: 'Дмитрий Васильев',
    specialty: 'Хирург',
    rating: 4.6,
    experience: 14,
    price: 5000,
    description: 'Хирург общей практики. Выполняет плановые и экстренные операции. Владеет современными хирургическими техниками.',
    photoUrl: 'https://example.com/doctor5.jpg',
    reviewCount: 21,
  },
];

export const simpleSpecialties = [
  'Все',
  'Терапевт',
  'Кардиолог',
  'Невролог',
  'Педиатр',
  'Хирург',
  'Офтальмолог',
  'Отоларинголог',
  'Дерматолог',
  'Гинеколог',
];